In [8]:
def test():
    print("test() for function")
    return
test()

test() for function


In [6]:
class demo:
    def  test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()



test() for the class and method


In [12]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=demo1()
p1.fact(5)#120


120

In [14]:
class demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("p1=",self.p1)
        print("p2=",self.p2)
c1=demo2()
c1.accept(10,20)
c1.display()

p1= 10
p2= 20


In [16]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [2]:
class Person(object):
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
    
class Employee(Person):
    def isEmployee(self):
        return True
    
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())
emp1=Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


### python numpy

In [3]:
list=[1,2,3,4]
print(list)

[1, 2, 3, 4]


In [1]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [4]:
list=[1,2,3,4]
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
int32


In [5]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
s2=np.array([(1,2),(3,4),(5,6)])
print(s2.shape)

(2, 3)
(3, 2)


In [6]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
A=np.ones((4,3),dtype=np.int64)
print(A)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [9]:

A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [10]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:

np.arange(1,100,9)


array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [12]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [14]:

a1=np.array([(1,2,3),(4,5,6)])
print("First Row: ",a1[0])

First Row:  [1 2 3]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [3]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[4.70378812 4.58461527 4.20309652 3.56045214 3.91450487 6.15883922
 5.02409659 6.72382848 5.68753998 3.98919406]
min value= 3.560452136053759
max value= 6.723828476438769
mean value= 4.854995522853953
median value= 4.644201692499407


In [4]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [6]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [4]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

### pandas

In [1]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
    "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
    "Mobile Number":[99,44,55,22,33,41]}

b=pd.DataFrame(dict)
print(b)


     Name           EmailID  Mobile Number
0    Anil    anil@gmail.com             99
1   Akhil   akhil@gmail.com             44
2  Dinesh  dinesh@gmail.com             55
3  Harsha  harsha@gmail.com             22
4    Ajay    ajay@gmail.com             33
5  Kranth  kranth@gmail.com             41


In [3]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  Mobile Number
01    Anil    anil@gmail.com             99
02   Akhil   akhil@gmail.com             44
03  Dinesh  dinesh@gmail.com             55
04  Harsha  harsha@gmail.com             22
05    Ajay    ajay@gmail.com             33
06  Kranth  kranth@gmail.com             41
